import { Given, When, Then } from "@badeball/cypress-cucumber-preprocessor";

/* No duplicate steps, this one already in bokadePlatser.js
Given('that the user is on the homepage', () => {});*/

When('the user presses on {string}', (a) => {
  // TODO: implement step
  //ändra mening eller loopa
  cy.get('[href="/visningar"]').click()
});

Then('the user should be able to choose between 10 different movies by using a filter', () => {
  // TODO: implement step
  cy.wait(11000)
    .get('.screenings-selectors:nth-child(1)').select('Parasit')
  cy.wait(1000)
    .get('.screenings-selectors:nth-child(1)').select('Det sjunde inseglet')
  cy.wait(1000)
    .get('.screenings-selectors:nth-child(1)').select('Triangle of Sadness')
  cy.wait(1000)
    .get('.screenings-selectors:nth-child(1)').select('Titane')
  cy.wait(1000)
    .get('.screenings-selectors:nth-child(1)').select('Call me by your name')
  cy.wait(1000)
    .get('.screenings-selectors:nth-child(1)').select('Mio min Mio')
  cy.wait(1000)
    .get('.screenings-selectors:nth-child(1)').select('Aliens Abducted My Parents')
  cy.wait(1000)
    .get('.screenings-selectors:nth-child(1)').select('Rubber')
  cy.wait(1000)
    .get('.screenings-selectors:nth-child(1)').select('The Blue Hour')
  cy.wait(1000)
    .get('.screenings-selectors:nth-child(1)').select('The Green Mile')
  cy.wait(1000)
});

/* No duplicate steps, this one already in bokadePlatser.js
Given('that the user is on the homepage', () => {});*/

/* No duplicate steps, this one already above
When('the user presses on the header {string}', (a) => {});*/

Then('the user should be able to choose between 2 different salons', () => {
  // TODO: implement step
  cy.wait(11000)
    .get('p.screenings-p').contains('Stora salongen')
    cy.contains('Lilla salongen')
});

/* No duplicate steps, this one already in bokadePlatser.js
Given('that the user is on the homepage', () => {});*/

/* No duplicate steps, this one already above
When('the user presses on the header {string}', (a) => {});*/

Then('the user should be able to choose between 28 different dates to watch a movie', () => {
  // TODO: implement step
  cy.wait(11000)
    .get('.screenings-selectors:nth-child(3)').select('Vecka 39')
  cy.wait(1000)
    .get('.screenings-selectors:nth-child(4)').select('Söndag 1:a oktober')
  cy.wait(1000)
    .get('.screenings-selectors:nth-child(3)').select('Alla veckor')
  cy.wait(1000)
    .get('.screenings-selectors:nth-child(3)').select('Vecka 48')
  cy.wait(1000)
    .get('.screenings-selectors:nth-child(4)').select('Fredag 1:a december')
  cy.wait(1000)
    .get('.screenings-selectors:nth-child(4)').select('Alla Datum')
  cy.wait(1000)
    .get('.screenings-selectors:nth-child(4)').select('Söndag 3:e december')
  cy.wait(1000)
    .get('.screenings-selectors:nth-child(3)').select('Alla veckor')
  cy.wait(1000)
    .get('.screenings-selectors:nth-child(3)').select('Vecka 49')
  cy.wait(1000)
    .get('.screenings-selectors:nth-child(4)').select('Måndag 4:e december')
  cy.wait(1000)
    .get('.screenings-selectors:nth-child(4)').select('Alla Datum')
  cy.wait(1000)
    .get('.screenings-selectors:nth-child(4)').select('Tisdag 5:e december')
  cy.wait(1000)
    .get('.screenings-selectors:nth-child(4)').select('Alla Datum')
  cy.wait(1000)
    .get('.screenings-selectors:nth-child(4)').select('Onsdag 6:e december')
  cy.wait(1000)
    .get('.screenings-selectors:nth-child(4)').select('Alla Datum')
  cy.wait(1000)
    .get('.screenings-selectors:nth-child(4)').select('Torsdag 7:e december')
  cy.wait(1000)
    .get('.screenings-selectors:nth-child(4)').select('Alla Datum')
  cy.wait(1000)
    .get('.screenings-selectors:nth-child(4)').select('Fredag 8:e december')
  cy.wait(1000)
    .get('.screenings-selectors:nth-child(4)').select('Alla Datum')
  cy.wait(1000)
    .get('.screenings-selectors:nth-child(4)').select('Lördag 9:e december')
  cy.wait(1000)
    .get('.screenings-selectors:nth-child(4)').select('Alla Datum')
  cy.wait(1000)
    .get('.screenings-selectors:nth-child(4)').select('Söndag 10:e december')
  cy.wait(1000)
    .get('.screenings-selectors:nth-child(3)').select('Alla veckor')
  cy.wait(1000)
    .get('.screenings-selectors:nth-child(3)').select('Vecka 50')
  cy.wait(1000)
    .get('.screenings-selectors:nth-child(4)').select('Måndag 11:e december')
  cy.wait(1000)
    .get('.screenings-selectors:nth-child(4)').select('Alla Datum')
  cy.wait(1000)
    .get('.screenings-selectors:nth-child(4)').select('Tisdag 12:e december')
  cy.wait(1000)
    .get('.screenings-selectors:nth-child(4)').select('Alla Datum')
  cy.wait(1000)
    .get('.screenings-selectors:nth-child(4)').select('Onsdag 13:e december')
  cy.wait(1000)
    .get('.screenings-selectors:nth-child(4)').select('Alla Datum')
  cy.wait(1000)
    .get('.screenings-selectors:nth-child(4)').select('Torsdag 14:e december')
  cy.wait(1000)
    .get('.screenings-selectors:nth-child(4)').select('Alla Datum')
  cy.wait(1000)
    .get('.screenings-selectors:nth-child(4)').select('Fredag 15:e december')
  cy.wait(1000)
    .get('.screenings-selectors:nth-child(4)').select('Alla Datum')
  cy.wait(1000)
    .get('.screenings-selectors:nth-child(4)').select('Lördag 16:e december')
  cy.wait(1000)
    .get('.screenings-selectors:nth-child(4)').select('Alla Datum')
  cy.wait(1000)
    .get('.screenings-selectors:nth-child(4)').select('Söndag 17:e december')
  cy.wait(1000)
    .get('.screenings-selectors:nth-child(3)').select('Alla veckor')
  cy.wait(1000)
    .get('.screenings-selectors:nth-child(3)').select('Vecka 51')
  cy.wait(1000)
    .get('.screenings-selectors:nth-child(4)').select('Måndag 18:e december')
  cy.wait(1000)
    .get('.screenings-selectors:nth-child(4)').select('Alla Datum')
  cy.wait(1000)
    .get('.screenings-selectors:nth-child(4)').select('Tisdag 19:e december')
  cy.wait(1000)
    .get('.screenings-selectors:nth-child(4)').select('Alla Datum')
  cy.wait(1000)
    .get('.screenings-selectors:nth-child(4)').select('Onsdag 20:e december')
  cy.wait(1000)
    .get('.screenings-selectors:nth-child(4)').select('Alla Datum')
  cy.wait(1000)
    .get('.screenings-selectors:nth-child(4)').select('Torsdag 21:a december')
  cy.wait(1000)
    .get('.screenings-selectors:nth-child(4)').select('Alla Datum')
  cy.wait(1000)
    .get('.screenings-selectors:nth-child(4)').select('Fredag 22:a december')
  cy.wait(1000)
    .get('.screenings-selectors:nth-child(4)').select('Alla Datum')
  cy.wait(1000)
    .get('.screenings-selectors:nth-child(4)').select('Lördag 23:e december')
  cy.wait(1000)
    .get('.screenings-selectors:nth-child(4)').select('Alla Datum')
  cy.wait(1000)
    .get('.screenings-selectors:nth-child(4)').select('Söndag 24:e december')
  cy.wait(1000)
    .get('.screenings-selectors:nth-child(3)').select('Alla veckor')
  cy.wait(1000)
    .get('.screenings-selectors:nth-child(3)').select('Vecka 52')
  cy.wait(1000)
    .get('.screenings-selectors:nth-child(4)').select('Måndag 25:e december')
  cy.wait(1000)
    .get('.screenings-selectors:nth-child(4)').select('Alla Datum')
  cy.wait(1000)
    .get('.screenings-selectors:nth-child(4)').select('Onsdag 27:e december')
  cy.wait(1000)
    .get('.screenings-selectors:nth-child(4)').select('Alla Datum')
  cy.wait(1000)
    .get('.screenings-selectors:nth-child(4)').select('Torsdag 28:e december')
  cy.wait(1000)
    .get('.screenings-selectors:nth-child(4)').select('Alla Datum')
  cy.wait(1000)
    .get('.screenings-selectors:nth-child(4)').select('Lördag 30:e december')
  cy.wait(1000)
    
}); 
